server:
  port: 8999
  servlet:
    context-path: /feign #项目访问路径前缀
spring:
  security:
    user:
      name: user
      password: password123
  application:
    name: spring-cloud-feign
# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
